"""English display names by SKU — synced to product_catalog.PRODUCT_ROWS.

Regenerate: python scripts/generate_product_en_by_sku.py
"""
from __future__ import annotations

PRODUCT_EN_BY_SKU: dict[str, str] = {
    "HK-SLP-001": 'White slippers (size S)',
    "HK-SLP-002": 'White slippers (size M)',
    "HK-SLP-003": 'White slippers (size L)',
    "HK-SLP-004": 'White slippers (size XL)',
    "HK-SLP-005": "Children's slippers",
    "HK-SLP-006": 'Pool slippers',
    "HK-TWL-001": 'Bath towel (large)',
    "HK-TWL-002": 'Bath towel (medium)',
    "HK-TWL-003": 'Hand towel',
    "HK-TWL-004": 'Face towel',
    "HK-TWL-005": 'Foot towel',
    "HK-TWL-006": 'Bath mat',
    "HK-TWL-007": 'Pool towel',
    "HK-TWL-008": 'Pool cover-up shirt',
    "HK-BTH-001": 'Bathrobe (size M)',
    "HK-BTH-002": 'Bathrobe (size L)',
    "HK-BTH-003": 'Bathrobe (size XL)',
    "HK-BTH-004": 'Spare shower curtain',
    "HK-BTH-005": 'Non-slip bathroom mat',
    "HK-BED-001": 'Soft pillow',
    "HK-BED-002": 'Standard pillow',
    "HK-BED-003": 'Firm pillow',
    "HK-BED-004": 'Down pillow',
    "HK-BED-005": 'Hypoallergenic pillow',
    "HK-BED-006": 'Body pillow',
    "HK-BED-007": 'Silk pillow',
    "HK-BED-008": 'Leg rest pillow',
    "HK-BED-009": 'Light blanket',
    "HK-BED-010": 'Heavy blanket',
    "HK-BED-011": 'Duvet comforter',
    "HK-BED-012": 'Duvet cover',
    "HK-BED-013": 'Twin bed sheet set',
    "HK-BED-014": 'King bed sheet set',
    "HK-BED-015": 'Extra-large bed sheet set',
    "HK-BED-016": 'Pillowcase',
    "HK-BED-017": 'Body pillowcase',
    "HK-BED-018": 'Mattress pad',
    "HK-BED-019": 'Duvet blanket',
    "HK-BED-020": 'Clothes hanger',
    "HK-BED-021": 'Trouser hanger',
    "HK-BED-022": 'Luggage rack',
    "HK-LND-001": 'Laundry garment bag',
    "HK-LND-002": 'Laundry service form',
    "HK-LND-003": 'Do not disturb sign',
    "HK-LND-004": 'Please make up room sign',
    "HK-LND-005": 'Mesh laundry bag',
    "HK-LND-006": 'Spare clothes hangers',
    "HK-AMN-001": 'Shampoo',
    "HK-AMN-002": 'Conditioner',
    "HK-AMN-003": 'Body wash',
    "HK-AMN-004": 'Body lotion',
    "HK-AMN-005": 'Body lotion',
    "HK-AMN-006": 'Bar soap',
    "HK-AMN-007": 'Hand wash gel',
    "HK-AMN-008": 'Antibacterial hand gel',
    "HK-AMN-009": 'Mouthwash',
    "HK-AMN-010": 'Toothbrush set',
    "HK-AMN-011": 'Toothpaste sachet',
    "HK-AMN-012": 'Dental floss sachet',
    "HK-AMN-013": 'Shaving kit',
    "HK-AMN-014": 'Shaving foam can',
    "HK-AMN-015": 'Cotton swabs box',
    "HK-AMN-016": 'Sewing kit',
    "HK-AMN-017": 'Shower cap',
    "HK-AMN-018": 'Comb',
    "HK-AMN-019": 'Hairbrush',
    "HK-AMN-020": 'Bathroom amenity basket',
    "HK-AMN-021": 'Bath salts sachet',
    "HK-AMN-022": 'Body sponge',
    "HK-AMN-023": 'Undergarment laundry bag',
    "HK-AMN-024": 'Stationery and amenity kit',
    "HK-AMN-025": 'Room air freshener spray',
    "HK-AMN-026": 'Wet wipes pack',
    "HK-AMN-027": 'Face mask',
    "HK-AMN-028": 'Corrosion inhibitor sachet',
    "HK-AMN-029": 'Sunscreen sachet',
    "HK-AMN-030": 'Bathroom air freshener',
    "HK-HKP-001": 'Tissue box',
    "HK-HKP-002": 'Toilet paper roll',
    "HK-HKP-003": 'Toilet paper pack',
    "HK-HKP-004": 'Water glass',
    "HK-HKP-005": 'Coffee and tea glass',
    "HK-HKP-006": 'Coaster',
    "HK-HKP-007": 'Drinking water (500 ml bottle)',
    "HK-HKP-008": 'Drinking water (1 L bottle)',
    "HK-HKP-009": 'Sparkling mineral water',
    "HK-HKP-010": 'Coffee sachet set',
    "HK-HKP-011": 'Tea sachet set',
    "HK-HKP-012": 'Herbal tea sachet',
    "HK-HKP-013": 'Black or green tea sachet',
    "HK-HKP-014": 'Cocoa sachet',
    "HK-HKP-015": 'Sugar and creamer set',
    "HK-HKP-016": 'Honey stirrer and spoon set',
    "HK-HKP-017": 'Room trash bag roll',
    "HK-HKP-018": 'Bathroom waste bin',
    "HK-HKP-019": 'Ice bucket',
    "HK-HKP-020": 'Ice scoop',
    "HK-HKP-021": 'Ice bag',
    "HK-HKP-022": 'Notepad and pen set',
    "HK-HKP-023": 'Hotel directory',
    "HK-HKP-024": 'Matches',
    "HK-HKP-025": 'Boxed fruit juice',
    "HK-HKP-026": 'UHT milk carton',
    "HK-HKP-027": 'Yogurt cup',
    "HK-HKP-028": 'Bottle opener',
    "HK-HKP-029": 'Spare minibar glass',
    "HK-HKP-030": 'Minibar tray',
    "HK-MIN-001": 'Cola or soft drink can',
    "HK-MIN-002": 'Sugar-free soft drink can',
    "HK-MIN-003": 'Orange or apple juice bottle',
    "HK-MIN-004": 'Domestic beer bottle',
    "HK-MIN-005": 'Imported beer bottle',
    "HK-MIN-006": 'Red wine (glass bottle)',
    "HK-MIN-007": 'White wine (glass bottle)',
    "HK-MIN-008": 'Spirits and whisky (minibar)',
    "HK-MIN-009": 'Snack chips',
    "HK-MIN-010": 'Nuts or raisins pack',
    "HK-MIN-011": 'Chocolate bar',
    "HK-MIN-012": 'Biscuits pack',
    "HK-MIN-013": 'Energy drink can',
    "HK-MIN-014": 'Popcorn pack',
    "HK-MIN-015": 'Baked coconut pack',
    "HK-MIN-016": 'Candy or chewing gum pack',
    "HK-MIN-017": 'Cup ice cream',
    "HK-MIN-018": 'Honey sachet',
    "HK-EQP-001": 'Hair dryer',
    "HK-EQP-002": 'Iron',
    "HK-EQP-003": 'Ironing board',
    "HK-EQP-004": 'Crib',
    "HK-EQP-005": 'Rollaway bed',
    "HK-EQP-006": 'Dehumidifier',
    "HK-EQP-007": 'Shoe horn',
    "HK-EQP-008": 'Luggage stand',
    "HK-EQP-009": 'Umbrella',
    "HK-EQP-010": 'Power strip or extension cord',
    "HK-EQP-011": 'Plug adapter',
    "HK-EQP-012": 'Charging cable or USB cable',
    "HK-EQP-013": 'HDMI cable',
    "HK-EQP-014": 'Bluetooth speaker',
    "HK-EQP-015": 'Air purifier',
    "HK-EQP-016": 'Lunch box',
    "HK-EQP-017": 'Hot water kettle',
    "HK-EQP-018": 'Capsule coffee machine',
    "HK-EQP-019": 'Coffee machine capsules',
    "HK-EQP-020": 'Swim cap',
    "HK-EQP-021": 'Luggage scale',
    "HK-KID-001": "Children's toiletry kit",
    "HK-KID-002": "Children's pillow",
    "HK-KID-003": "Children's bed sheet set",
    "HK-KID-004": 'High chair',
    "HK-KID-005": 'Booster seat',
    "HK-KID-006": 'Coloring book',
    "HK-KID-007": 'Toy set',
    "HK-KID-008": 'Baby bathtub',
    "HK-KID-009": "Children's shampoo and lotion",
    "HK-KID-010": 'Potty seat',
    "HK-KID-011": 'Diapers pack',
    "HK-KID-012": 'Baby play mat',
    "HK-KID-013": 'Bottle warmer',
    "HK-ACC-001": 'Wheelchair',
    "HK-ACC-002": 'Shower chair',
    "HK-ACC-003": 'Grab bar set',
    "HK-ACC-004": 'Toilet seat riser',
    "HK-ACC-005": 'Hearing accessibility kit',
    "HK-ACC-006": 'Bed rail',
    "HK-ACC-007": 'Walking cane',
    "HK-ACC-008": 'Hearing aid',
    "HK-PUB-001": 'Wet floor sign',
    "HK-PUB-002": 'Toilet brush',
    "HK-PUB-003": 'Cleaning solution (public area)',
    "HK-PUB-004": 'Microfiber cloth (public area)',
    "HK-PUB-005": 'Rubber gloves',
    "HK-PUB-006": 'Trash bag roll (public area)',
    "HK-PUB-007": 'Paper hand towel pack',
    "HK-PUB-008": 'Glass cleaner',
    "HK-PUB-009": 'Broom and dustpan set',
    "HK-PUB-010": 'Mop bucket and handle set',
    "HK-PUB-011": 'Surface disinfectant',
    "HK-PUB-012": 'Rust stain remover',
    "HK-PUB-013": 'Dishwashing liquid (gallon)',
    "HK-PUB-014": 'Sponge or scrub pad',
    "HK-PUB-015": 'Color-coded trash bags',
    "HK-PUB-016": 'Lidded trash bin (public area)',
    "HK-PUB-017": 'Limescale remover',
    "HK-PUB-018": 'Carpet cleaner',
    "HK-PLS-001": 'Large pool towel',
    "HK-PLS-002": 'Medium pool towel',
    "HK-PLS-003": 'Pool cover-up robe',
    "HK-PLS-004": 'Blue pool slippers',
    "HK-PLS-005": 'Swim cap',
    "HK-PLS-006": 'Sunglasses',
    "HK-PLS-007": 'Sunscreen (pool)',
    "HK-PLS-008": "Children's swim ring",
    "HK-PLS-009": 'Adult swim ring',
    "HK-PLS-010": 'Life jacket',
    "HK-PLS-011": 'Pool chair cover',
    "HK-PLS-012": 'Pool chair cushion',
    "HK-PLS-013": 'Sun umbrella',
    "HK-PLS-014": 'Wet swimsuit bag',
    "HK-PLS-015": 'Pool sanitizer (spare)',
    "HK-SPA-001": 'Spa robe set',
    "HK-SPA-002": 'Spa slippers',
    "HK-SPA-003": 'Spa bath towel',
    "HK-SPA-004": 'Disposable spa underwear set',
    "HK-SPA-005": 'Spa shower cap',
    "HK-SPA-006": 'Disposable spa slippers',
    "HK-SPA-007": 'Massage oil (small bottle)',
    "HK-SPA-008": 'Spa bath salts sachet',
    "HK-SPA-009": 'Hot stone foot massage set',
    "HK-SPA-010": 'Massage table sheet',
    "HK-MIN-019": 'Sparkling water (small bottle)',
    "HK-MIN-020": 'Small soft drink can',
    "HK-MIN-021": 'Pineapple juice can',
    "HK-MIN-022": 'Lime soda can',
    "HK-MIN-023": 'Coconut water can',
    "HK-MIN-024": 'Rosé wine (glass bottle)',
    "HK-MIN-025": 'Mini gin bottle',
    "HK-MIN-026": 'Mini vodka bottle',
    "HK-MIN-027": 'Mini rum bottle',
    "HK-MIN-028": 'Mixed fruit juice box',
    "HK-MIN-029": 'Iced tea can',
    "HK-MIN-030": 'Ready-to-drink coffee can',
    "HK-GST-001": 'Lens cleaning cloth',
    "HK-GST-002": 'Stationery set (spare)',
    "HK-GST-003": 'Desk pad',
    "HK-GST-004": 'Room power strip',
    "HK-GST-005": 'Reading lamp',
    "HK-GST-006": 'Makeup mirror',
    "HK-GST-007": 'Ice bucket',
    "HK-GST-008": 'Water heater',
    "HK-GST-009": 'Seat cushion',
    "HK-GST-010": 'Dining table cloth',
    "HK-GST-011": 'Plastic cutlery set',
    "HK-GST-012": 'Plate and bowl set',
    "HK-SEC-001": 'Small fire extinguisher',
    "HK-SEC-002": 'Fire blanket',
    "HK-SEC-003": 'In-room first aid kit',
    "HK-SEC-004": 'Emergency exit sign',
    "HK-SEC-005": 'Emergency light (spare battery)',
    "HK-SEC-006": 'Cut-resistant gloves',
    "HK-SEC-007": 'Safety goggles',
    "HK-SEC-008": 'No smoking sticker',
    "HK-LIN-001": 'Laundry detergent (gallon)',
    "HK-LIN-002": 'Fabric softener (gallon)',
    "HK-LIN-003": 'Bleach (gallon)',
    "HK-LIN-004": 'Soiled linen bag',
    "HK-LIN-005": 'Guest name clothing labels',
    "HK-LIN-006": 'Plastic shirt hanger',
    "HK-LIN-007": 'Plastic trouser hanger',
    "HK-LIN-008": 'Garment plastic bag roll',
    "HK-LIN-009": 'Laundry airer cloth',
    "HK-LIN-010": 'Fabric stain remover',
    "HK-AMN-031": 'Shaving cream sachet',
    "HK-AMN-032": 'Talcum powder sachet',
    "HK-AMN-033": 'Adult diapers pack',
    "HK-AMN-034": 'Sanitary pads pack',
    "HK-AMN-035": 'Condoms',
    "HK-AMN-036": 'Intimate care product sachet',
    "HK-AMN-037": 'Saline nasal spray sachet',
    "HK-SVC-001": 'Room cleaning (stayover guest)',
    "HK-SVC-002": 'Turndown service',
    "HK-SVC-003": 'Light room cleaning',
    "HK-SVC-004": 'Deep cleaning',
    "HK-SVC-005": 'Carpet cleaning',
    "HK-SVC-006": 'Minibar restock and check',
    "FO-SVC-001": 'Wake-up call service',
    "FO-SVC-002": 'ABF box order',
    "FO-SVC-003": 'Luggage receive (front desk)',
    "FO-SVC-004": 'Luggage pickup',
    "FO-SVC-005": 'Deliver luggage to room',
    "FO-SVC-006": 'Move luggage between rooms',
    "HK-SVC-010": 'Express laundry service',
    "HK-SVC-011": 'Laundry pickup',
    "HK-SVC-012": 'Shoe shine service',
    "HK-SVC-013": 'In-room flowers or gift setup',
    "HK-SVC-014": 'Birthday surprise setup',
    "HK-SVC-015": 'Honeymoon room setup',
    "HK-SVC-016": 'Allergy-free room preparation',
    "HK-SVC-017": 'Pillow menu change',
    "HK-SVC-018": 'Bed linen change',
    "HK-SVC-019": 'Towel replacement',
    "HK-SVC-020": 'Full amenity restock',
    "HK-SVC-021": 'Balcony cleaning',
    "HK-SVC-022": 'Trash and recycling collection',
    "HK-SVC-023": 'Post-checkout room inspection',
    "HK-SVC-024": 'VIP pre-arrival room setup',
    "HK-SVC-025": 'Pet-friendly room setup',
    "HK-SVC-026": 'Lost and found search',
    "HK-SVC-027": 'Guest document or fax delivery',
    "HK-SVC-028": 'Complimentary water and coffee refill',
    "HK-SVC-029": 'In-room desk setup',
    "HK-SVC-030": 'Extra bed setup',
    "HK-SVC-031": 'In-room kitchenette cleaning',
    "HK-SVC-032": 'In-room refrigerator cleaning',
    "HK-SVC-033": 'Curtain or drape change',
    "HK-SVC-034": 'Room odor treatment',
    "HK-SVC-035": 'In-room luggage organization',
    "HK-SVC-036": 'Dry cleaning (outsourced)',
    "HK-SVC-037": 'Pressing service',
    "HK-SVC-038": 'Slipper laundry service',
    "HK-SVC-099": 'Other housekeeping — specify in notes',
    "MT-BLB-001": 'Incandescent light bulb',
    "MT-BLB-002": 'LED light bulb',
    "MT-BLB-003": 'Downlight bulb',
    "MT-BLB-004": 'Bathroom heat lamp bulb',
    "MT-BLB-005": 'In-safe light bulb',
    "MT-PLM-001": 'Faucet aerator filter',
    "MT-PLM-002": 'Shower head',
    "MT-PLM-003": 'Shower hose',
    "MT-PLM-004": 'Toilet flush valve kit',
    "MT-PLM-005": 'Sink drain stopper',
    "MT-PLM-006": 'Supply or drain hose',
    "MT-PLM-007": "Plumber's putty tube",
    "MT-PLM-008": 'Bidet spray hose',
    "MT-PLM-009": 'Toilet flush handle',
    "MT-PLM-010": 'Spare faucet',
    "MT-ELC-001": 'TV remote control',
    "MT-ELC-002": 'AA batteries (pack)',
    "MT-ELC-003": 'AAA batteries (pack)',
    "MT-ELC-004": 'Safe battery (9 V)',
    "MT-ELC-005": 'Thermostat battery',
    "MT-ELC-006": 'Smoke detector battery',
    "MT-ELC-007": 'HDMI cable',
    "MT-ELC-008": 'Ethernet cable',
    "MT-ELC-009": 'Power outlet or switch',
    "MT-ELC-010": 'Emergency light bulb',
    "MT-ELC-011": 'Fuse or breaker (spare)',
    "MT-ELC-012": 'Minibar light bulb',
    "MT-HKP-001": 'Door stop wedge',
    "MT-HKP-002": 'Clothes hook',
    "MT-HKP-003": 'Door hinge set',
    "MT-HKP-004": 'Door closer',
    "MT-HKP-005": 'Door handle set',
    "MT-HKP-006": 'Spare key or test card',
    "MT-HKP-007": 'Door security seal tape',
    "MT-HKP-008": 'Curtain or blind set',
    "MT-HKP-009": 'Spare bathroom mirror',
    "MT-HKP-010": 'Touch-up wall paint can',
    "MT-HKP-011": 'Door and window sealant',
    "MT-HKP-012": 'Bathroom floor mat pad',
    "MT-HVAC-001": 'AC remote control',
    "MT-HVAC-002": 'Room AC filter',
    "MT-HVAC-003": 'AC capacitor (spare)',
    "MT-HVAC-004": 'Room air filter pad',
    "MT-FUR-001": 'Furniture screws and bolts set',
    "MT-FUR-002": 'Chair or table caster set',
    "MT-FUR-003": 'Wood or furniture glue',
    "MT-FUR-004": 'Spare table leg',
    "MT-FUR-005": 'Chair leg floor protectors',
    "MT-PLS-001": 'Pool pump spare parts kit',
    "MT-PLS-002": 'Pool filter cartridge',
    "MT-PLS-003": 'Pool sanitizer (gallon)',
    "MT-PLS-004": 'Pool vacuum hose',
    "MT-PLS-005": 'Underwater light bulb',
    "MT-PLS-006": 'Pool pipe cap',
    "MT-KIT-001": 'Gas hose (kitchen)',
    "MT-KIT-002": 'Spare gas burner head',
    "MT-KIT-003": 'Drain pipe cap',
    "MT-KIT-004": 'Washing machine inlet hose',
    "MT-KIT-005": 'Dryer inlet hose',
    "MT-KIT-006": 'Washing machine drive belt',
    "MT-KIT-007": 'Range hood filter',
    "MT-KIT-008": 'Gas stove igniter bulb',
    "MT-SFT-001": 'Fire extinguisher',
    "MT-SFT-002": 'Fire hose reel',
    "MT-SFT-003": 'Dust mask',
    "MT-SFT-004": 'Heat-resistant gloves',
    "MT-SFT-005": 'Safety rope',
    "MT-SFT-006": 'Spare emergency exit sign',
    "MT-ELC-013": 'Corridor light bulb',
    "MT-ELC-014": 'Lobby light bulb',
    "MT-ELC-015": 'Elevator light bulb',
    "MT-HKP-013": 'Spare door glass panel',
    "MT-HKP-014": 'Door weatherstrip roll',
    "MT-HKP-015": 'AC drain float',
    "MT-HVAC-005": 'Evaporator coil cleaner',
    "MT-HVAC-006": 'AC condensate drain hose',
    "MT-SVC-001": 'AC not cooling repair',
    "MT-SVC-002": 'AC leaking water',
    "MT-SVC-003": 'AC making loud noise',
    "MT-SVC-004": 'Door adjustment (squeaking)',
    "MT-SVC-005": 'Door not closing properly',
    "MT-SVC-006": 'Touch-up wall paint',
    "MT-SVC-007": 'TV not working or no signal',
    "MT-SVC-008": 'TV remote not working',
    "MT-SVC-009": 'Internet or Wi-Fi not working',
    "MT-SVC-010": 'In-room Bluetooth speaker issue',
    "MT-SVC-011": 'Water leak or pipe leak',
    "MT-SVC-012": 'Toilet clogged',
    "MT-SVC-013": 'Toilet running continuously',
    "MT-SVC-014": 'Sink leaking or clogged',
    "MT-SVC-015": 'Shower no water or no hot water',
    "MT-SVC-016": 'No hot water',
    "MT-SVC-017": 'No cold water',
    "MT-SVC-018": 'Power outlet not working',
    "MT-SVC-019": 'Room lights off or flickering',
    "MT-SVC-020": 'Light switch not working',
    "MT-SVC-021": "In-room safe won't open",
    "MT-SVC-022": 'In-room safe code reset',
    "MT-SVC-023": "Window or balcony won't open",
    "MT-SVC-024": 'Curtain or blind stuck',
    "MT-SVC-025": 'Furniture repair',
    "MT-SVC-026": 'Wobbly chair or table',
    "MT-SVC-027": 'Key card or door lock issue',
    "MT-SVC-028": "Room door won't open",
    "MT-SVC-029": 'Minibar or fridge not cooling',
    "MT-SVC-030": 'Minibar inventory change',
    "MT-SVC-031": 'Room phone not working',
    "MT-SVC-032": 'Intercom or doorbell not working',
    "MT-SVC-033": 'Mirror damaged or broken',
    "MT-SVC-034": 'Bathroom mirror fogging',
    "MT-SVC-035": 'Room odor or drain smell',
    "MT-SVC-036": 'Smoke detector alarm',
    "MT-SVC-037": 'Fire sprinkler system issue',
    "MT-SVC-038": 'Elevator or escalator report',
    "MT-SVC-039": 'Swimming pool equipment issue',
    "MT-SVC-040": 'Fitness equipment issue',
    "MT-SVC-041": 'Pest control request',
    "MT-SVC-042": 'Water heater reset',
    "MT-SVC-043": 'Thermostat not adjustable',
    "MT-SVC-044": 'Heated floor not working',
    "MT-SVC-045": 'USB charging port not working',
    "MT-SVC-046": 'Bathtub leaking or clogged',
    "MT-SVC-047": 'In-room coffee machine not working',
    "MT-SVC-048": 'In-room air purifier not working',
    "MT-SVC-049": 'In-room hair dryer not working',
    "MT-SVC-050": 'In-room iron not working',
    "MT-SVC-051": 'Sliding glass door stuck',
    "MT-SVC-052": "Balcony door won't lock",
    "MT-SVC-053": 'Mechanical noise in room',
    "MT-SVC-054": 'In-room safe making noise',
    "MT-SVC-055": 'Gas or burning smell in room',
    "MT-SVC-099": 'Other maintenance — specify in notes',
}
